include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

linter:
  rules:
    unnecessary_this: false
    library_private_types_in_public_api: false
    prefer_relative_imports: true
    prefer_single_quotes: true
    unnecessary_await_in_return: false
    prefer_final_locals: true
    prefer_final_fields: true
    avoid_unused_constructor_parameters: true
    always_declare_return_types: true
    require_trailing_commas: true
